name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: SMTestCR1.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t SMTestCR1.azurecr.io/python-sample-vscode-flask-tutorial:${{ github.sha }}
            docker push SMTestCR1.azurecr.io/python-sample-vscode-flask-tutorial:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ SECRETS.AZURE_CREDENTIALS }}

        - name: 'Deploy to Azure Container Instances'
          uses: azure/aci-deploy@v1
          with:
            resource-group: SMResourceGroup
            name: python-sample-vscode-flask-tutorial
            image: SMTestCR1.azurecr.io/python-sample-vscode-flask-tutorial:${{ github.sha }}
            ports: 80 8080
            dns-name-label: python-sample-vscode-flask-tutorial
            registry-login-server: SMTestCR1.azurecr.io
            registry-username: ${{ SECRETS.REGISTRY_USERNAME }}
            registry-password: ${{ SECRETS.REGISTRY_PASSWORD }}
            location: eastus